### ISSUE TITLE
Prevent the standard Pretty Printer usage from SE80 and combine with Code Inspector Pretty Printer Check

### ISSUE THREAD

**Issue by AndreasSchaller-STELACON** [SAP/abap-cleaner#128] opened 2023-10-02 14:46 UTC
Hi, 

abap-cleaner is really very helpful and a great time saver. 
**Very very good Job in the right direction !!!** 

But when different developers work in a team, then suddenly new problems appear.

We have some projects where an ATC check is done before releasing a transport request in the development system. 
Specifically, the Code Inspector check "Check Pretty Print State" is performed, which is mandatory.

Due to the fact that with abap-cleaner a 2nd "Pretty Printer" was introduced, there is competing behavior with the old "Pretty Printer". Especially the reformatting from calling function module, which we find useful to reduce the number of lines, creates problems. 

If another developer calls the "old" Pretty Printer later (either from ADT or SE80), the code is formatted back to the old representation. This only creates unnecessary changes in the source code history later, which have nothing to do with actual changes to the functionality. (messing up code history)

This eternal back and forth within a distributed team is organizationally impossible to handle without hard constraints.
There are always a few fools who just can't get it together or come into the project as newcomers who haven't heard of abap-cleaner.

Therefore, it must be possible that the **"old" Pretty Printer is "redirected"** to the new abap-cleaner **or** at least that the old one is **switched off** with the indication that **only the abap-cleaner can and must be used.**

Also the check in the **Code Inspector should check for the centrally managed rules of the abap-cleaner**.

I would have no problem if this is only available via copy/paste in SE80, because you force developers to switch to ABAP in Eclipse. **The form-based class editor (SE24) should be able to be switched off completely for everyone** (at least in development system).  

I know this won't happen overnight, but in order for abap-cleaner to fly at supersonic speeds, these issues need to be addressed.

And I don't just want supersonic speed, I want the ability to beam an entire packages into cleanly formatted code. :-)
And no "bad superhero" should unintentionally throw the clean code over again just because he presses SHIFT+F1 in SE24 with form-based editor.

**Comment by jelliottp** [comment] 2023-10-02 15:07
In general I agree with your assessment, and have run into some similar situations.
> 
> If another developer calls the "old" Pretty Printer later (either from ADT or SE80), the code is formatted back to the old representation. This only creates unnecessary changes in the source code history later, which have nothing to do with actual changes to the functionality. (messing up code history)
> 
> This eternal back and forth within a distributed team is organizationally impossible to handle without hard constraints. There are always a few fools who just can't get it together or come into the project as newcomers who haven't heard of abap-cleaner.
> 
Do you have examples where the standard pretty printer is applying a different format? 

I have run into this and [posted about it before](https://github.com/SAP/abap-cleaner/issues/73), but have been told this is very system version-dependent, and in later system versions abap-cleaner and the standard formatter are aligned.

**Comment by AndreasSchaller-STELACON** [comment] 2023-10-02 16:38
Hi Josh,
**CL_CI_TEST_PRETTY_PRINT** is the class being used in check-variant at ATC-check.
Here the example regarding call of function modules

Formated with abap-cleaner
```
    CALL FUNCTION 'POPUP_TO_CONFIRM'
      EXPORTING  titlebar              = TEXT-003
                 diagnose_object       = 'YDEMO_TEXT'
                 text_question         = TEXT-004
                 text_button_1         = TEXT-001
                 icon_button_1         = 'ICON_SYSTEM_BACK'
                 text_button_2         = TEXT-002
                 icon_button_2         = 'ICON_SUBMIT'
                 display_cancel_button = ''
                 popup_type            = 'ICON_MESSAGE_WARNING'
      IMPORTING  answer                = lv_answer
      TABLES     parameter             = lt_parameter
      EXCEPTIONS text_not_found        = 1
                 OTHERS                = 2.
```
later "destroyed" with standard pretty-printer
```
    CALL FUNCTION 'POPUP_TO_CONFIRM'
      EXPORTING
        titlebar              = TEXT-003
        diagnose_object       = 'YDEMO_TEXT'
        text_question         = TEXT-004
        text_button_1         = TEXT-001
        icon_button_1         = 'ICON_SYSTEM_BACK'
        text_button_2         = TEXT-002
        icon_button_2         = 'ICON_SUBMIT'
        display_cancel_button = ''
        popup_type            = 'ICON_MESSAGE_WARNING'
      IMPORTING
        answer                = lv_answer
      TABLES
        parameter             = lt_parameter
      EXCEPTIONS
        text_not_found        = 1
        OTHERS                = 2.
```

**Comment by fabianlupa** [comment] 2023-10-02 17:05
I don't believe there is a way to disable pretty printer. The easiest solution would be an implicit enhancement in function module `PRETTY_PRINTER` checking for the program name and exiting early. Calling abap-cleaner instead from the backend seems infeasible.

**Comment by jmgrassau** [comment] 2023-10-05 11:33
Hi Andreas, 

thanks for opening this issue. I'm afraid, this is out of scope for ABAP cleaner, because while ABAP cleaner is trying to improve ABAP code, this project has no influence on Code Inspector / ATC checks / SE24 settings or behavior; and since ABAP cleaner runs completely local, its settings (i.e. profiles) are not centrally managed. 

If formatting of function calls is a specific concern and leads to "edit wars", maybe the best compromise would be to align the settings of this cleanup rule with what Pretty Printer does (or even deactivate the cleanup rule). Most of what ABAP cleaner does is not in conflict with (or "destroyed" by) PrettyPrinter (with very few exceptions), so there would still be a lot of improvement. 

And of course keep trying to convince people to use ADT… but I know that's easier said than done if someone has used SAP GUI for a long time. But then, ADT has also been around for a long time now! 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment] 2023-10-23 06:43
Hi Andreas, 

an expert from the ABAP Platform now confirmed that PrettyPrinter settings are always user-dependent, so there is no system-wide, cross-user way to deactivate PrettyPrinter – unless you change data for all users in table RSEUMOD. But I guess that's not a solution that would help the team spirit. 

So, closing this for now, hoping that ABAP cleaner can contribute a bit to convincing people to finally move to ADT… 

Kind regards,
Jörg-Michael

**Closed by jmgrassau** 2023-10-23 06:43 UTC
Labels: out of scope
