### ISSUE TITLE
Feature request: Clipboard clean-up in the Eclipse plugin

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#155] opened 2023-10-18 06:32 UTC
Hi Jörg-Michael, cleaning up code stored in the clipboard is only possible using the stand-alone application right now. Would it be possible to include this feature in the Eclipse plugin? In our current SAP system release, there are still some development objects (e.g. enhancements) where the ADT editor can't be used yet. I'd like to be able to copy code from SAP GUI to my clipboard, use the ABAP Cleaner, then paste it back into SAP GUI.  

This use case doesn't really happen that often to warrant keeping the stand-alone application updated in parallel, so I'd like to avoid that. 😉

**Comment by ConjuringCoffee** [comment] 2023-10-18 07:54
Wow, your speed is impressive! Now let me reward that with an additional feature request... 😇 Would it be possible to make the function available if the active tab is showing the SAP GUI?

The ABAP Cleaner can only be accessed using the menu option "Source code":
![image](https://github.com/SAP/abap-cleaner/assets/72548231/1300c39d-d891-4cbe-b318-793135a966e1)

This section isn't available when the active tab shows the SAP GUI:
![image](https://github.com/SAP/abap-cleaner/assets/72548231/6c6feb83-1e05-4f36-8625-f2322284056e)

**Comment by jmgrassau** [comment] 2023-10-18 08:35
Hi ConjuringCoffee, 

I forwarded this question to a colleague who'd know better about this, but my feeling is that this won't be possible. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment] 2023-10-23 05:16
Hi ConjuringCoffee, 

and here's version 1.8.0, allowing to paste any ABAP code into the read-only preview! :-) As with the stand-alone version, all code blocks such as ```IF ... ENDIF``` must be complete in the pasted code. 

I will let you know when I hear news about SAP GUI inside ADT, but closing this for now. 

Kind regards,
Jörg-Michael

**Closed by jmgrassau** 2023-10-23 05:16 UTC
Labels: enhancement

**Comment by jmgrassau** [comment] 2023-10-23 07:16
Hi ConjuringCoffee, 

thanks for this nice reward ;-)

> Wow, your speed is impressive! Now let me reward that with an additional feature request... 😇 
> Would it be possible to make the function available if the active tab is showing the SAP GUI?

The colleague I asked has confirmed that this is not possible, because ADT has no information on what is shown, selected etc. in the embedded GUI. Therefore, no "Source Code" menu is shown, and there is no way of running ABAP cleaner on the code inside the embedded GUI. 

But then, who would want to edit ABAP code in SE80 when they have ADT!  :-)

Menu "Source Code" works, of course, if SAP GUI is opened with this option…
![image](https://github.com/SAP/abap-cleaner/assets/79639298/2bc7db16-df02-4694-bdb9-2b72cdeafc6e)
… and code is then indeed displayed inside of an ADT text editor. 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment] 2023-11-02 12:24
Thanks for the new clipboard feature! 

> But then, who would want to edit ABAP code in SE80 when they have ADT! :-)

Just to make it clear, this would be required when working in objects in which ADT can't be used yet. Because the "Source Code" menu isn't displayed, you need to navigate to another ADT tab, access the ABAP Cleaner there, and then navigate back to the SAP GUI tab. A little bit cumbersome, but it works 😉
