### ISSUE TITLE
Error: cannot insert a left sibling to a token that closes a level

### ISSUE THREAD

**Issue by FirdousP** [SAP/abap-cleaner#99] opened 2023-08-31 05:16 UTC
Hi ,

Getting the error, when running a custom Class in ABAP cleaner
![image](https://github.com/SAP/abap-cleaner/assets/141395854/a67de771-c32d-449c-a6a3-54e34b33f5cb)

Log in the mentioned path "line 4,484: cannot insert a left sibling to a token that closes a level"

Code line 4484
![image](https://github.com/SAP/abap-cleaner/assets/141395854/05a9fdef-b1e7-4c2c-9aa2-fa47cca94c49)

Kindly suggest on how this error can be resolved.

**Comment by jmgrassau** [comment] 2023-09-03 20:27
Hi FirdousP, 

thanks for reporting this issue – however, I am afraid I would need more context (i.e. more of the surrounding code) to be able to reproduce this error. The error message is indeed a bit odd for this line 4484, because in ABAP clenaer, a "token that closes a level" would typically be a closing parenthesis ")" or brace "}".

Maybe you could try to reduce your code sample to a minimal example that triggers the error? Otherwise, if you don't feel comfortable to post the whole method here, you might as well email it to "abap-cleaner at sap dot com" (which is just received by another SAP colleague and myself). 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment] 2023-09-22 08:33
Hi FirdousP, 

as mentioned, without some more context, I am afraid I can't reproduce this, so closing this issue for now. Please feel free to reopen the issue if you have some example to help reproduce it.

Kind regards,
Jörg-Michael

**Closed by jmgrassau** 2023-09-22 08:33 UTC
Labels: no defect
