### ISSUE TITLE
Wrong warning: " TODO: variable is assigned but never used (ABAP cleaner)

### ISSUE THREAD

**Issue by VladGhitulescu** [SAP/abap-cleaner#189] opened 2023-11-09 08:24 UTC
Hey,

I've got the warning 

`" TODO: variable is assigned but never used (ABAP cleaner)`

even when the variable **_ls_adrc_chk_** was used

![CleanShot 2023-11-09 at 09 19 44](https://github.com/SAP/abap-cleaner/assets/3112128/3cfbd5a5-dd3c-4fdb-9c9c-427628c0c0c6)

Could you please check this?

Thanks!

Regards,
Vlad

**Comment by jmgrassau** [comment] 2023-11-09 08:47
Hi Vlad, 

at least from the code shown above, this is not a bug but a feature! :-) All three lines _write_ to ```ls_adrc_chk``` (or components of it), but the variable is never used in a _read_ access (by assigning it to another variable, passing it as a parameter to another method etc.), so it would be worth checking why information is stored in ```ls_adrc_chk```  when this information is indeed never needed! 

Kind regards,
Jörg-Michael

**Comment by VladGhitulescu** [comment] 2023-11-09 08:54
Hi JM,


oh I understand! 

You're absolutely right - I'm not ready coding yet but keep hitting CMD 4 only to get the code-clarity through ABAP Cleaner :-)

Sorry for the false alarm and thanks for the explanation!


Regards,
Vlad

**Comment by jmgrassau** [comment] 2023-11-09 09:03
Hi Vlad, 

thanks and no worries! Okay, I think then we can close the issue. 

Kind regards,
Jörg-Michael

**Closed by jmgrassau** 2023-11-09 09:03 UTC
Labels: no defect
