### ISSUE TITLE
CLASS ... DEFINITION DEFERRED not working

### ISSUE THREAD

**Issue by ruhnla** [SAP/abap-cleaner#142] opened 2023-10-11 16:11 UTC
The ABAP cleaner stops immediately when the command CLASS ... DEFINITION DEFERRED is found with the error message "Opening 'CLASS' not closed." (ABAP version 7.50)

![image](https://github.com/SAP/abap-cleaner/assets/117291081/8bfc3303-76e6-4bc4-9912-d7a1be27ceae)

Is this a bug or a feature or missing functionality?

**Comment by jmgrassau** [comment] 2023-10-12 06:57
Hi ruhnla, 

that's odd, actually ABAP cleaner does consider CLASS ... DEFINITION DEFERRED and does not expect an ENDCLASS here. Could you maybe try to create a minimal example for this (removing everything that doesn't trigger the error)? Do you use the plug-in or the stand-alone ABAP cleaner, and which version of it? 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment] 2023-10-12 11:42
Hi Lars, 

I see – it's the colon! I didn't expect ```CLASS``` to be followed by ```:```, so if you remove that, things will work (and I shall enhance the code to consider this case, too).

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment] 2023-10-12 11:47
Hi Lars, 

okay, that wasn't difficult, this will be considered in the next release.

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment] 2023-10-12 12:03
`:` seems to be one of the greatest threats to the ABAP Cleaner 😄

**Comment by jmgrassau** [comment] 2023-10-15 19:05
Hi ConjuringCoffee, 

yes, along with comments and pragmas that's indeed the case! From this perspective, life is rather easy for a compiler, which can do a pre-processing step and 
* throw away any whitespace for good, 
* remove all comments, 
* expand all chains, 
* apply all macros, 
* …

and only then start doing its actual job (well, admittedly, there might be some complexity in _that_ part…). 

But not for ABAP cleaner! Because we care a lot about whitespace and alignment, have to stay aware that there may be any number of comments anywhere (including between any two tokens inside of a statement), must mind the pragmas (including in wrong places) and the chain colons … 

So, unfortunately, so far, there was always a constellation that wasn't yet considered. But let's hope the new "stress test" which I mentioned in #147 helps to identify more of those in advance! :-) 

And anyway, diligently writing regression tests, so at least we can be sure that whatever issue came up once for _someone_ won't come up again for _anyone!_ 🙂

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment] 2023-10-16 13:14
Hi Lars, 

thanks again for reporting this – this issue should now be fixed in version 1.7.2, which was just released. 

Kind regards,
Jörg-Michael

**Closed by jmgrassau** 2023-10-16 13:14 UTC
Labels: bug
