### ISSUE TITLE
The configuration-window has no CANCEL-SAVE-buttons anymore

### ISSUE THREAD

**Issue by VladGhitulescu** [SAP/abap-cleaner#197] opened 2023-11-11 11:30 UTC
Hey,

please take a look:

![CleanShot 2023-11-11 at 12 28 31](https://github.com/SAP/abap-cleaner/assets/3112128/ec1e3882-5058-450e-b477-e82d30f73ec0)

Regards,
Vlad

**Comment by jmgrassau** [comment] 2023-11-11 16:46
Hi Vlad, 

thanks a lot for reporting this. Unfortunately, life is too short to understand Java layout managers. In this case, this was caused by the long rule description. Will be fixed with the next release!

Kind regards,
Jörg-Michael

**Comment by VladGhitulescu** [comment] 2023-11-12 07:29
:-D
Thanks JM!

**Comment by jmgrassau** [comment] 2023-11-13 21:22
Hi Vlad, 

thanks again for reporting this issue – this should now be fixed with version 1.11.1, which was just released! 

Kind regards,
Jörg-Michael

**Closed by jmgrassau** 2023-11-13 21:22 UTC
Labels: bug
