### ISSUE TITLE
Code indentation issue

### ISSUE THREAD

**Issue by Falcon7EH** [SAP/abap-cleaner#248] opened 2024-02-12 10:14 UTC
The code indentation doesn't seem to work correctly for case statements,
if the WHEN block is defined a row below the "COND #(" part.
Every time the cleaner is carried out, the block moves 4 chars to the right,
which could lead to a syntax error, if the maximum number of allowed chars per rows are reached.

![media_12 02 2024_10-47-37](https://github.com/SAP/abap-cleaner/assets/159769459/a4237da6-0340-498e-8b33-ac657d6735ee)

Used cleaner settings: 
[recommended.zip](https://github.com/SAP/abap-cleaner/files/14237117/recommended.zip)

**Comment by jmgrassau** [comment] 2024-02-27 15:49
Hi Falcon7EH, 

ah, nice observation! This is caused by the "Indent lines" rule when there are two commands on the same line, and the second command spans multiple lines. Will be fixed with the next release!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment] 2024-02-27 17:46
Hi Falcon7EH, 

thanks again for opening this issue! This bug should now be resolved with version 1.13.2, which was just released!

Kind regards,
Jörg-Michael

**Closed by jmgrassau** 2024-02-27 17:46 UTC
Labels: bug
